
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Unit Tests
      - name: Run Unit Tests
        run: npm test
        env:
          NODE_ENV: ${{ matrix.environment }}

      # Integration Tests
      - name: Run Integration Tests
        run: npm run integration-test
        env:
          NODE_ENV: ${{ matrix.environment }}

      # End-to-End Tests
      - name: Run E2E Tests
        run: npm run e2e
        env:
          NODE_ENV: ${{ matrix.environment }}
